apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gcp-quota-exporter.fullname" . }}
  labels:
    {{- include "gcp-quota-exporter.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "gcp-quota-exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "gcp-quota-exporter.selectorLabels" . | nindent 8 }}
    {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "gcp-quota-exporter.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /app/credentials.json
            - name: GOOGLE_PROJECT_ID
              value: {{ .Values.gcpProject }}
          ports:
            - name: http
              containerPort: 9592
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- if .Values.serviceAccountSecret }}
            - name: stackdriver-service-account
              mountPath: /app/credentials.json
              subPath: {{ .Values.subPath }}
            {{- end}}
      volumes:
      {{- if .Values.serviceAccountSecret }}
      - name: stackdriver-service-account
        secret:
          secretName: {{ .Values.serviceAccountSecret | quote }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}