{{- range $type, $secrets :=  $.Values.secrets -}}
{{- range $secretName, $secretKeys :=  $secrets -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    heritage: {{ $.Release.Service | quote }}
    release: {{ $.Release.Name | quote }}
    chart: "{{$.Chart.Name}}-{{$.Chart.Version}}"
type: {{ $type }}
data:
{{- range $key, $value :=  $secretKeys }}
    {{ $key }}: {{ $value | b64enc | quote -}}
{{ end }}
{{ end -}}
{{ end -}}
